unit RiggVar.FB.Color;

interface

uses
  UITypes;

type
  TRggColor = TAlphaColor;

  TRggColors = class
  public
    class var
    Alpha: TRggColor;
    Aliceblue: TRggColor;
    Antiquewhite: TRggColor;
    Aqua: TRggColor;
    Aquamarine: TRggColor;
    Azure: TRggColor;
    Beige: TRggColor;
    Bisque: TRggColor;
    Black: TRggColor;
    Blanchedalmond: TRggColor;
    Blue: TRggColor;
    Blueviolet: TRggColor;
    Brown: TRggColor;
    Burlywood: TRggColor;
    Cadetblue: TRggColor;
    Chartreuse: TRggColor;
    Chocolate: TRggColor;
    Coral: TRggColor;
    Cornflowerblue: TRggColor;
    Cornsilk: TRggColor;
    Crimson: TRggColor;
    Cyan: TRggColor;
    Darkblue: TRggColor;
    Darkcyan: TRggColor;
    Darkgoldenrod: TRggColor;
    Darkgray: TRggColor;
    Darkgreen: TRggColor;
    Darkgrey: TRggColor;
    Darkkhaki: TRggColor;
    Darkmagenta: TRggColor;
    Darkolivegreen: TRggColor;
    Darkorange: TRggColor;
    Darkorchid: TRggColor;
    Darkred: TRggColor;
    Darksalmon: TRggColor;
    Darkseagreen: TRggColor;
    Darkslateblue: TRggColor;
    Darkslategray: TRggColor;
    Darkslategrey: TRggColor;
    Darkturquoise: TRggColor;
    Darkviolet: TRggColor;
    Deeppink: TRggColor;
    Deepskyblue: TRggColor;
    Dimgray: TRggColor;
    Dimgrey: TRggColor;
    Dodgerblue: TRggColor;
    Firebrick: TRggColor;
    Floralwhite: TRggColor;
    Forestgreen: TRggColor;
    Fuchsia: TRggColor;
    Gainsboro: TRggColor;
    Ghostwhite: TRggColor;
    Gold: TRggColor;
    Goldenrod: TRggColor;
    Gray: TRggColor;
    Green: TRggColor;
    Greenyellow: TRggColor;
    Grey: TRggColor;
    Honeydew: TRggColor;
    Hotpink: TRggColor;
    Indianred: TRggColor;
    Indigo: TRggColor;
    Ivory: TRggColor;
    Khaki: TRggColor;
    Lavender: TRggColor;
    Lavenderblush: TRggColor;
    Lawngreen: TRggColor;
    Lemonchiffon: TRggColor;
    Lightblue: TRggColor;
    Lightcoral: TRggColor;
    Lightcyan: TRggColor;
    Lightgoldenrodyellow: TRggColor;
    Lightgray: TRggColor;
    Lightgreen: TRggColor;
    Lightgrey: TRggColor;
    Lightpink: TRggColor;
    Lightsalmon: TRggColor;
    Lightseagreen: TRggColor;
    Lightskyblue: TRggColor;
    Lightslategray: TRggColor;
    Lightslategrey: TRggColor;
    Lightsteelblue: TRggColor;
    Lightyellow: TRggColor;
    LtGray: TRggColor;
    MedGray: TRggColor;
    DkGray: TRggColor;
    MoneyGreen: TRggColor;
    LegacySkyBlue: TRggColor;
    Cream: TRggColor;
    Lime: TRggColor;
    Limegreen: TRggColor;
    Linen: TRggColor;
    Magenta: TRggColor;
    Maroon: TRggColor;
    Mediumaquamarine: TRggColor;
    Mediumblue: TRggColor;
    Mediumorchid: TRggColor;
    Mediumpurple: TRggColor;
    Mediumseagreen: TRggColor;
    Mediumslateblue: TRggColor;
    Mediumspringgreen: TRggColor;
    Mediumturquoise: TRggColor;
    Mediumvioletred: TRggColor;
    Midnightblue: TRggColor;
    Mintcream: TRggColor;
    Mistyrose: TRggColor;
    Moccasin: TRggColor;
    Navajowhite: TRggColor;
    Navy: TRggColor;
    Oldlace: TRggColor;
    Olive: TRggColor;
    Olivedrab: TRggColor;
    Orange: TRggColor;
    Orangered: TRggColor;
    Orchid: TRggColor;
    Palegoldenrod: TRggColor;
    Palegreen: TRggColor;
    Paleturquoise: TRggColor;
    Palevioletred: TRggColor;
    Papayawhip: TRggColor;
    Peachpuff: TRggColor;
    Peru: TRggColor;
    Pink: TRggColor;
    Plum: TRggColor;
    Powderblue: TRggColor;
    Purple: TRggColor;
    Red: TRggColor;
    Rosybrown: TRggColor;
    Royalblue: TRggColor;
    Saddlebrown: TRggColor;
    Salmon: TRggColor;
    Sandybrown: TRggColor;
    Seagreen: TRggColor;
    Seashell: TRggColor;
    Sienna: TRggColor;
    Silver: TRggColor;
    Skyblue: TRggColor;
    Slateblue: TRggColor;
    Slategray: TRggColor;
    Slategrey: TRggColor;
    Snow: TRggColor;
    Springgreen: TRggColor;
    Steelblue: TRggColor;
    Tan: TRggColor;
    Teal: TRggColor;
    Thistle: TRggColor;
    Tomato: TRggColor;
    Turquoise: TRggColor;
    Violet: TRggColor;
    Wheat: TRggColor;
    White: TRggColor;
    Whitesmoke: TRggColor;
    Yellow: TRggColor;
    Yellowgreen: TRggColor;

    WindowWhite: TRggColor;
    ColorF9F9F9: TRggColor;
    Color372E69: TRggColor;
    Color333333: TRggColor;

    Null: TRggColor;

  public
    class constructor Create;
    class function ColorFromRGB(R, G, B: Byte): TRggColor;
  end;

implementation

  class constructor TRggColors.Create;
  begin
    Alpha := TAlphaColor($FF000000);

    Null := Alpha or TAlphaColor($FFFFFF);

    WindowWhite := Alpha or TAlphaColor($F0F0F0);

    ColorF9F9F9 := Alpha or TAlphaColor($F9F9F9);
    Color372E69 := Alpha or TAlphaColor($372E69);
    Color333333 := Alpha or TAlphaColor($333333);

    Aliceblue := Alpha or TAlphaColor($F0F8FF);
    Antiquewhite := Alpha or TAlphaColor($FAEBD7);
    Aqua := Alpha or TAlphaColor($00FFFF);
    Aquamarine := Alpha or TAlphaColor($7FFFD4);
    Azure := Alpha or TAlphaColor($F0FFFF);
    Beige := Alpha or TAlphaColor($F5F5DC);
    Bisque := Alpha or TAlphaColor($FFE4C4);
    Black := Alpha or TAlphaColor($000000);
    Blanchedalmond := Alpha or TAlphaColor($FFEBCD);
    Blue := Alpha or TAlphaColor($0000FF);
    Blueviolet := Alpha or TAlphaColor($8A2BE2);
    Brown := Alpha or TAlphaColor($A52A2A);
    Burlywood := Alpha or TAlphaColor($DEB887);
    Cadetblue := Alpha or TAlphaColor($5F9EA0);
    Chartreuse := Alpha or TAlphaColor($7FFF00);
    Chocolate := Alpha or TAlphaColor($D2691E);
    Coral := Alpha or TAlphaColor($FF7F50);
    Cornflowerblue := Alpha or TAlphaColor($6495ED);
    Cornsilk := Alpha or TAlphaColor($FFF8DC);
    Crimson := Alpha or TAlphaColor($DC143C);
    Cyan := Alpha or TAlphaColor($00FFFF);
    Darkblue := Alpha or TAlphaColor($00008B);
    Darkcyan := Alpha or TAlphaColor($008B8B);
    Darkgoldenrod := Alpha or TAlphaColor($B8860B);
    Darkgray := Alpha or TAlphaColor($A9A9A9);
    Darkgreen := Alpha or TAlphaColor($006400);
    Darkgrey := Alpha or TAlphaColor($A9A9A9);
    Darkkhaki := Alpha or TAlphaColor($BDB76B);
    Darkmagenta := Alpha or TAlphaColor($8B008B);
    Darkolivegreen := Alpha or TAlphaColor($556B2F);
    Darkorange := Alpha or TAlphaColor($FF8C00);
    Darkorchid := Alpha or TAlphaColor($9932CC);
    Darkred := Alpha or TAlphaColor($8B0000);
    Darksalmon := Alpha or TAlphaColor($E9967A);
    Darkseagreen := Alpha or TAlphaColor($8FBC8F);
    Darkslateblue := Alpha or TAlphaColor($483D8B);
    Darkslategray := Alpha or TAlphaColor($2F4F4F);
    Darkslategrey := Alpha or TAlphaColor($2F4F4F);
    Darkturquoise := Alpha or TAlphaColor($00CED1);
    Darkviolet := Alpha or TAlphaColor($9400D3);
    Deeppink := Alpha or TAlphaColor($FF1493);
    Deepskyblue := Alpha or TAlphaColor($00BFFF);
    Dimgray := Alpha or TAlphaColor($696969);
    Dimgrey := Alpha or TAlphaColor($696969);
    Dodgerblue := Alpha or TAlphaColor($1E90FF);
    Firebrick := Alpha or TAlphaColor($B22222);
    Floralwhite := Alpha or TAlphaColor($FFFAF0);
    Forestgreen := Alpha or TAlphaColor($228B22);
    Fuchsia := Alpha or TAlphaColor($FF00FF);
    Gainsboro := Alpha or TAlphaColor($DCDCDC);
    Ghostwhite := Alpha or TAlphaColor($F8F8FF);
    Gold := Alpha or TAlphaColor($FFD700);
    Goldenrod := Alpha or TAlphaColor($DAA520);
    Gray := Alpha or TAlphaColor($808080);
    Green := Alpha or TAlphaColor($008000);
    Greenyellow := Alpha or TAlphaColor($ADFF2F);
    Grey := Alpha or TAlphaColor($808080);
    Honeydew := Alpha or TAlphaColor($F0FFF0);
    Hotpink := Alpha or TAlphaColor($FF69B4);
    Indianred := Alpha or TAlphaColor($CD5C5C);
    Indigo := Alpha or TAlphaColor($4B0082);
    Ivory := Alpha or TAlphaColor($FFFFF0);
    Khaki := Alpha or TAlphaColor($F0E68C);
    Lavender := Alpha or TAlphaColor($E6E6FA);
    Lavenderblush := Alpha or TAlphaColor($FFF0F5);
    Lawngreen := Alpha or TAlphaColor($7CFC00);
    Lemonchiffon := Alpha or TAlphaColor($FFFACD);
    Lightblue := Alpha or TAlphaColor($ADD8E6);
    Lightcoral := Alpha or TAlphaColor($F08080);
    Lightcyan := Alpha or TAlphaColor($E0FFFF);
    Lightgoldenrodyellow := Alpha or TAlphaColor($FAFAD2);
    Lightgray := Alpha or TAlphaColor($D3D3D3);
    Lightgreen := Alpha or TAlphaColor($90EE90);
    Lightgrey := Alpha or TAlphaColor($D3D3D3);
    Lightpink := Alpha or TAlphaColor($FFB6C1);
    Lightsalmon := Alpha or TAlphaColor($FFA07A);
    Lightseagreen := Alpha or TAlphaColor($20B2AA);
    Lightskyblue := Alpha or TAlphaColor($87CEFA);
    Lightslategray := Alpha or TAlphaColor($778899);
    Lightslategrey := Alpha or TAlphaColor($778899);
    Lightsteelblue := Alpha or TAlphaColor($B0C4DE);
    Lightyellow := Alpha or TAlphaColor($FFFFE0);
    LtGray := Alpha or TAlphaColor($C0C0C0);
    MedGray := Alpha or TAlphaColor($A0A0A0);
    DkGray := Alpha or TAlphaColor($808080);
    MoneyGreen := Alpha or TAlphaColor($C0DCC0);
    LegacySkyBlue := Alpha or TAlphaColor($F0CAA6);
    Cream := Alpha or TAlphaColor($F0FBFF);
    Lime := Alpha or TAlphaColor($00FF00);
    Limegreen := Alpha or TAlphaColor($32CD32);
    Linen := Alpha or TAlphaColor($FAF0E6);
    Magenta := Alpha or TAlphaColor($FF00FF);
    Maroon := Alpha or TAlphaColor($800000);
    Mediumaquamarine := Alpha or TAlphaColor($66CDAA);
    Mediumblue := Alpha or TAlphaColor($0000CD);
    Mediumorchid := Alpha or TAlphaColor($BA55D3);
    Mediumpurple := Alpha or TAlphaColor($9370DB);
    Mediumseagreen := Alpha or TAlphaColor($3CB371);
    Mediumslateblue := Alpha or TAlphaColor($7B68EE);
    Mediumspringgreen := Alpha or TAlphaColor($00FA9A);
    Mediumturquoise := Alpha or TAlphaColor($48D1CC);
    Mediumvioletred := Alpha or TAlphaColor($C71585);
    Midnightblue := Alpha or TAlphaColor($191970);
    Mintcream := Alpha or TAlphaColor($F5FFFA);
    Mistyrose := Alpha or TAlphaColor($FFE4E1);
    Moccasin := Alpha or TAlphaColor($FFE4B5);
    Navajowhite := Alpha or TAlphaColor($FFDEAD);
    Navy := Alpha or TAlphaColor($000080);
    Oldlace := Alpha or TAlphaColor($FDF5E6);
    Olive := Alpha or TAlphaColor($808000);
    Olivedrab := Alpha or TAlphaColor($6B8E23);
    Orange := Alpha or TAlphaColor($FFA500);
    Orangered := Alpha or TAlphaColor($FF4500);
    Orchid := Alpha or TAlphaColor($DA70D6);
    Palegoldenrod := Alpha or TAlphaColor($EEE8AA);
    Palegreen := Alpha or TAlphaColor($98FB98);
    Paleturquoise := Alpha or TAlphaColor($AFEEEE);
    Palevioletred := Alpha or TAlphaColor($DB7093);
    Papayawhip := Alpha or TAlphaColor($FFEFD5);
    Peachpuff := Alpha or TAlphaColor($FFDAB9);
    Peru := Alpha or TAlphaColor($CD853F);
    Pink := Alpha or TAlphaColor($FFC0CB);
    Plum := Alpha or TAlphaColor($DDA0DD);
    Powderblue := Alpha or TAlphaColor($B0E0E6);
    Purple := Alpha or TAlphaColor($800080);
    Red := Alpha or TAlphaColor($FF0000);
    Rosybrown := Alpha or TAlphaColor($BC8F8F);
    Royalblue := Alpha or TAlphaColor($4169E1);
    Saddlebrown := Alpha or TAlphaColor($8B4513);
    Salmon := Alpha or TAlphaColor($FA8072);
    Sandybrown := Alpha or TAlphaColor($F4A460);
    Seagreen := Alpha or TAlphaColor($2E8B57);
    Seashell := Alpha or TAlphaColor($FFF5EE);
    Sienna := Alpha or TAlphaColor($A0522D);
    Silver := Alpha or TAlphaColor($C0C0C0);
    Skyblue := Alpha or TAlphaColor($87CEEB);
    Slateblue := Alpha or TAlphaColor($6A5ACD);
    Slategray := Alpha or TAlphaColor($708090);
    Slategrey := Alpha or TAlphaColor($708090);
    Snow := Alpha or TAlphaColor($FFFAFA);
    Springgreen := Alpha or TAlphaColor($00FF7F);
    Steelblue := Alpha or TAlphaColor($4682B4);
    Tan := Alpha or TAlphaColor($D2B48C);
    Teal := Alpha or TAlphaColor($008080);
    Thistle := Alpha or TAlphaColor($D8BFD8);
    Tomato := Alpha or TAlphaColor($FF6347);
    Turquoise := Alpha or TAlphaColor($40E0D0);
    Violet := Alpha or TAlphaColor($EE82EE);
    Wheat := Alpha or TAlphaColor($F5DEB3);
    White := Alpha or TAlphaColor($FFFFFF);
    Whitesmoke := Alpha or TAlphaColor($F5F5F5);
    Yellow := Alpha or TAlphaColor($FFFF00);
    Yellowgreen := Alpha or TAlphaColor($9ACD32);
  end;

  class function TRggColors.ColorFromRGB(R, G, B: Byte): TRggColor;
  var
    acr: TAlphaColorRec;
  begin
    acr.R := R;
    acr.G := G;
    acr.B := B;
    acr.A := 255;
    result := acr.Color;
  end;

end.
